export const seedContent = {
  opportunities: [
    {
      id: "opp-seed-1",
      title: "Bushcare Volunteer Program",
      organization: "Landcare Australia",
      location: "Multiple locations, AU",
      type: "Volunteer",
      deadline: "Always open",
      summary: "Join local habitat restoration projects and practical conservation days.",
      tags: ["Volunteer", "Community", "Habitat"],
      url: "https://landcareaustralia.org.au/",
      source: "Landcare Australia",
      publishedAt: "2026-01-15T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-ghd",
      title: "Graduate Program — Environment & Earth Sciences",
      organization: "GHD",
      location: "Brisbane, Sydney, Melbourne, Perth · AU",
      type: "Graduate",
      deadline: "Rolling annual intake",
      summary:
        "Structured rotations across contaminated land, water, EIA, and sustainability teams. Mentoring, chartership pathways, and multi-disciplinary projects.",
      tags: ["Graduate", "Consulting", "Environmental science"],
      url: "https://www.ghd.com/en/careers/early-careers",
      source: "EcoVerse curated",
      publishedAt: "2026-02-01T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-aecom",
      title: "Australia Students & Graduates — Sustainability & Environment",
      organization: "AECOM",
      location: "Australia-wide",
      type: "Graduate",
      deadline: "Check intake dates",
      summary:
        "Graduate pathways in environmental planning, impact assessment, resilience, and remediation. Work on major infrastructure and net-zero programs.",
      tags: ["Graduate", "EIA", "Sustainability"],
      url: "https://aecom.com/careers/australia-students-and-graduates",
      source: "EcoVerse curated",
      publishedAt: "2026-02-10T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-wsp",
      title: "Graduate Program — Environment & Planning",
      organization: "WSP in Australia",
      location: "Major cities, AU",
      type: "Graduate",
      deadline: "Annual campaign",
      summary:
        "Graduate roles spanning ecology, approvals, contaminated sites, and climate adaptation on transport, water, and urban projects.",
      tags: ["Graduate", "Consulting", "Planning"],
      url: "https://www.wsp.com/en-au/careers",
      source: "EcoVerse curated",
      publishedAt: "2026-02-12T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-arup",
      title: "Graduate — Sustainability & Climate (Australia)",
      organization: "Arup",
      location: "Sydney, Melbourne, Brisbane",
      type: "Graduate",
      deadline: "Intake varies",
      summary:
        "Sustainability consulting, climate risk, circular economy, and environmental performance on buildings and infrastructure.",
      tags: ["Graduate", "Climate", "Consulting"],
      url: "https://www.arup.com/careers/early-careers",
      source: "EcoVerse curated",
      publishedAt: "2026-02-15T00:00:00.000Z",
    },
    {
      id: "opp-seed-entry-jacobs",
      title: "Environmental Scientist — Early Career (Consulting)",
      organization: "Jacobs",
      location: "Australia",
      type: "Entry",
      deadline: "Open listings",
      summary:
        "Field and desk work on impact assessment, monitoring, and compliance for resources, defence, and water clients.",
      tags: ["Environmental science", "Consulting", "EIA"],
      url: "https://jacobs.taleo.net/",
      source: "EcoVerse curated",
      publishedAt: "2026-03-01T00:00:00.000Z",
    },
    {
      id: "opp-seed-entry-tetra",
      title: "Graduate / Junior Consultant — Contaminated Land",
      organization: "Tetra Tech",
      location: "Sydney · Melbourne",
      type: "Graduate",
      deadline: "As advertised",
      summary:
        "Site investigations, groundwater, remediation design, and reporting under senior consultants. Strong fit for env. science grads.",
      tags: ["Graduate", "Contaminated land", "Consulting"],
      url: "https://www.tetratech.com/en/careers",
      source: "EcoVerse curated",
      publishedAt: "2026-03-05T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-ey",
      title: "Graduate — Climate Change & Sustainability Services",
      organization: "EY Australia",
      location: "Sydney, Melbourne, Brisbane",
      type: "Graduate",
      deadline: "Graduate recruitment window",
      summary:
        "ESG disclosure, climate risk, decarbonisation, and nature-related advisory for ASX and government clients.",
      tags: ["Graduate", "ESG", "Consulting"],
      url: "https://www.ey.com/en_au/careers/students-and-graduates",
      source: "EcoVerse curated",
      publishedAt: "2026-03-08T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-deloitte",
      title: "Graduate — Sustainability & Climate Engineering",
      organization: "Deloitte Australia",
      location: "Australia",
      type: "Graduate",
      deadline: "Graduate program cycle",
      summary:
        "Climate modelling support, net-zero strategy, sustainable finance, and environmental assurance projects in multidisciplinary teams.",
      tags: ["Graduate", "Climate", "Consulting"],
      url: "https://www2.deloitte.com/au/en/pages/careers/topics/graduates.html",
      source: "EcoVerse curated",
      publishedAt: "2026-03-10T00:00:00.000Z",
    },
    {
      id: "opp-seed-research-csiro",
      title: "CSIRO Early Research Career / Postdoctoral Pathways",
      organization: "CSIRO",
      location: "Australia",
      type: "Research",
      deadline: "Rolling",
      summary:
        "Environmental science, land and water, oceans, and climate teams — research support roles and postdoc opportunities across national labs.",
      tags: ["Research", "Environmental science", "Graduate"],
      url: "https://www.csiro.au/en/careers",
      source: "EcoVerse curated",
      publishedAt: "2026-03-12T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-aps",
      title: "Australian Government Graduate Program — Environment Stream",
      organization: "Australian Public Service",
      location: "Canberra · national",
      type: "Graduate",
      deadline: "Annual campaign",
      summary:
        "Rotations in environment, climate, agriculture, and water policy. Policy analysis, legislation, and program delivery.",
      tags: ["Graduate", "Policy", "Public sector"],
      url: "https://www.apsjobs.gov.au/",
      source: "EcoVerse curated",
      publishedAt: "2026-03-15T00:00:00.000Z",
    },
    {
      id: "opp-seed-grad-nsw",
      title: "NSW Government Graduate Program — Environment & Heritage",
      organization: "NSW Government",
      location: "Sydney · regional NSW",
      type: "Graduate",
      deadline: "See NSW jobs",
      summary:
        "Graduate roles in national parks, biodiversity, planning, and compliance — mix of policy and operational delivery.",
      tags: ["Graduate", "Government", "Environmental science"],
      url: "https://www.nsw.gov.au/working-for-nsw",
      source: "EcoVerse curated",
      publishedAt: "2026-03-18T00:00:00.000Z",
    },
    {
      id: "opp-seed-intern-unsw",
      title: "Environmental Science — Honours & Industry Placement Partners",
      organization: "Australian universities (example pathway)",
      location: "NSW · VIC · QLD",
      type: "Internship",
      deadline: "Semester-based",
      summary:
        "Course-linked placements with consultancies and regulators — use your faculty’s careers office to match environmental science and consulting projects.",
      tags: ["Internship", "Environmental science", "Students"],
      url: "https://www.unsw.edu.au/",
      source: "EcoVerse curated",
      publishedAt: "2026-03-20T00:00:00.000Z",
    },
  ],
  events: [
    {
      id: "event-seed-nsw-landcare-2026",
      title: "NSW Landcare and Local Land Services Conference 2026",
      host: "Landcare NSW & Local Land Services",
      date: "2026-10-27",
      format: "In person",
      location: "Corowa, NSW",
      summary:
        "Regional conference for Landcare groups, farmers, and volunteers — workshops, field trips, and networking (typically late October; confirm dates on the organiser site).",
      url: "https://nswlandcareconference.com.au/",
      source: "Landcare NSW",
      publishedAt: "2025-09-01T00:00:00.000Z",
    },
    {
      id: "event-seed-national-landcare-2027",
      title: "National Landcare Conference 2027",
      host: "Landcare Australia",
      date: "2027-09-06",
      format: "Hybrid",
      location: "Adelaide Convention Centre, SA",
      summary:
        "National forum for community Landcare, agriculture, and restoration — multi-day program (public schedule: early September 2027 in Adelaide).",
      url: "https://nationallandcareconference.org.au/",
      source: "Landcare Australia",
      publishedAt: "2025-09-01T00:00:00.000Z",
    },
    {
      id: "event-seed-ozwater-2026",
      title: "Ozwater 2026",
      host: "Australian Water Association",
      date: "2026-05-05",
      format: "In person",
      location: "Melbourne Convention Centre, VIC",
      summary: "Australia’s flagship water conference — technical papers, careers fair, and student sessions.",
      url: "https://www.awa.asn.au/",
      source: "Australian Water Association",
      publishedAt: "2025-10-01T00:00:00.000Z",
    },
    {
      id: "event-seed-clean-energy-2026",
      title: "Clean Energy Summit 2026",
      host: "Clean Energy Council",
      date: "2026-07-21",
      format: "In person",
      location: "Sydney, NSW",
      summary: "Policy, finance, and technology sessions across renewable energy and storage — major networking for graduates and career changers.",
      url: "https://www.cleanenergycouncil.org.au/",
      source: "Clean Energy Council",
      publishedAt: "2025-10-15T00:00:00.000Z",
    },
    {
      id: "event-seed-eianz-2026",
      title: "EIANZ Annual Conference 2026",
      host: "Environment Institute of Australia and New Zealand",
      date: "2026-11-12",
      format: "Hybrid",
      location: "Brisbane, QLD",
      summary: "Professional development, technical streams, and early-career meetups for environmental practitioners.",
      url: "https://www.eianz.org/",
      source: "EIANZ",
      publishedAt: "2025-08-01T00:00:00.000Z",
    },
    {
      id: "event-seed-esa-2026",
      title: "Ecological Society of Australia Conference 2026",
      host: "Ecological Society of Australia",
      date: "2026-11-24",
      format: "In person",
      location: "Perth, WA",
      summary: "Research talks, field excursions, and student awards spanning Australian ecology and conservation science.",
      url: "https://www.ecolsoc.org.au/",
      source: "Ecological Society of Australia",
      publishedAt: "2025-07-01T00:00:00.000Z",
    },
    {
      id: "event-seed-wed-2026",
      title: "World Environment Day — Community planting & talks",
      host: "Council & Landcare networks (various)",
      date: "2026-06-05",
      format: "In person",
      location: "Multiple cities, AU",
      summary: "Local councils and groups host planting days, clean-ups, and sustainability talks — check your nearest council.",
      url: "https://www.unep.org/",
      source: "EcoVerse curated",
      publishedAt: "2025-12-01T00:00:00.000Z",
    },
    {
      id: "event-seed-national-tree-day-2026",
      title: "National Tree Day — community planting",
      host: "Planet Ark & partners",
      date: "2026-07-26",
      format: "In person",
      location: "Nationwide, AU",
      summary: "Volunteer planting weekends — ideal for students building practical conservation experience.",
      url: "https://treeday.planetark.org/",
      source: "Planet Ark",
      publishedAt: "2025-11-01T00:00:00.000Z",
    },
    {
      id: "event-seed-reef-restoration-2026",
      title: "Coral reef restoration & monitoring field school",
      host: "James Cook University / partners",
      date: "2026-09-14",
      format: "In person",
      location: "Townsville, QLD",
      summary: "Hands-on weeks for marine science students — snorkel surveys, lab skills, and career pathways in reef management.",
      url: "https://www.jcu.edu.au/",
      source: "EcoVerse curated",
      publishedAt: "2025-10-20T00:00:00.000Z",
    },
    {
      id: "event-seed-carbon-webinar-2026",
      title: "Carbon markets & biodiversity credits — intro webinar",
      host: "Carbon Market Institute",
      date: "2026-04-08",
      format: "Online",
      location: "Online",
      summary: "Free webinar for graduates on how carbon and nature markets work in Australia.",
      url: "https://carbonmarketinstitute.org/",
      source: "Carbon Market Institute",
      publishedAt: "2026-01-10T00:00:00.000Z",
    },
    {
      id: "event-seed-bushfire-resilience-2026",
      title: "Community bushfire resilience & cultural burning forum",
      host: "Regional NRM / Fire agencies (example)",
      date: "2026-08-19",
      format: "Hybrid",
      location: "Bega, NSW",
      summary: "Panel on preparedness, Indigenous cultural burning, and environmental careers in fire-adapted landscapes.",
      url: "https://www.rfs.nsw.gov.au/",
      source: "EcoVerse curated",
      publishedAt: "2025-11-15T00:00:00.000Z",
    },
    {
      id: "event-seed-wetland-field-day-2026",
      title: "Wetland bird ID & water quality field day",
      host: "BirdLife Australia & local catchment group",
      date: "2026-05-17",
      format: "In person",
      location: "Werribee, VIC",
      summary: "Volunteer training day — surveying, water testing, and pathways into ecology and catchment roles.",
      url: "https://www.birdlife.org.au/",
      source: "BirdLife Australia",
      publishedAt: "2025-12-10T00:00:00.000Z",
    },
    {
      id: "event-seed-climate-careers-night-2026",
      title: "Climate careers night — startups & policy",
      host: "Climate Salad",
      date: "2026-10-29",
      format: "In person",
      location: "Carlton, VIC",
      summary: "Meet hiring teams from climate tech and advocacy — student-friendly networking.",
      url: "https://www.climatesalad.com/",
      source: "Climate Salad",
      publishedAt: "2025-09-20T00:00:00.000Z",
    },
    {
      id: "event-seed-student-sustainability-2026",
      title: "Student sustainability showcase & careers fair",
      host: "UNSW Sustainability Society",
      date: "2026-11-15",
      format: "In person",
      location: "UNSW Sydney, NSW",
      summary: "Student projects expo plus employer stalls across consulting, government, and NGOs.",
      url: "https://www.unsw.edu.au/",
      source: "EcoVerse curated",
      publishedAt: "2025-08-15T00:00:00.000Z",
    },
  ],
  articles: [],
  memberships: [
    {
      id: "member-1",
      organization: "Environment Institute of Australia and New Zealand",
      type: "Student & Professional Membership",
      benefits:
        "Events, mentoring programs, member rates, and national professional network access.",
      joinLink: "https://www.eianz.org/membership",
    },
    {
      id: "member-2",
      organization: "Australasian Land and Groundwater Association",
      type: "Emerging Professionals Membership",
      benefits:
        "Technical sessions, conference discounts, and career development workshops.",
      joinLink: "https://landandgroundwater.com/membership",
    },
    {
      id: "member-3",
      organization: "Soil Science Australia",
      type: "Professional & Student Membership",
      benefits:
        "National Soils Conference discounts, Soil Crumbs bulletin, CSIRO Publishing discount, CPSS accreditation pathway, branch events and soil science awards.",
      joinLink: "https://www.soilscienceaustralia.org.au/membership",
    },
    {
      id: "member-4",
      organization: "Australian Water Association",
      type: "Individual & Young Water Professional",
      benefits:
        "Ozwater and state conference rates, technical journals, mentoring, YWP networks, and national policy forums.",
      joinLink: "https://www.awa.asn.au/Membership",
    },
    {
      id: "member-5",
      organization: "Australian Association for Environmental Education",
      type: "Individual & Student Membership",
      benefits:
        "Australian Journal of Environmental Education, eeBulletin, discounted workshops, Learning Circles, and member resources hub.",
      joinLink: "https://www.aaee.org.au/join-now/",
    },
    {
      id: "member-6",
      organization: "Waste Management and Resource Recovery Association of Australia",
      type: "Professional Membership",
      benefits:
        "National conference, technical working groups, policy submissions, webinars, and sector networking across waste and circular economy.",
      joinLink: "https://www.wmrr.asn.au/Web/Web/Join_WMRR/Become_a_Member.aspx",
    },
    {
      id: "member-7",
      organization: "Environmental Health Australia",
      type: "Professional Membership",
      benefits:
        "National newsletter, webinars and CPD discounts, online community, and advocacy for environmental health practice.",
      joinLink: "https://www.eh.org.au/membership",
    },
    {
      id: "member-8",
      organization: "Institute of Public Works Engineering Australasia",
      type: "Member Grades",
      benefits:
        "Asset management and sustainability events, technical papers, certification pathways, and local division networks.",
      joinLink: "https://www.ipwea.org/membership",
    },
    {
      id: "member-9",
      organization: "BirdLife Australia",
      type: "Supporter & Guardian",
      benefits:
        "Conservation programs, surveys and volunteering, member magazine, and advocacy for threatened birds and habitats.",
      joinLink: "https://www.birdlife.org.au/support-us/join-us/",
    },
    {
      id: "member-10",
      organization: "Clean Energy Council",
      type: "Corporate & Associate",
      benefits:
        "Industry data, installer accreditation schemes, policy briefings, Clean Energy Summit, and market intelligence.",
      joinLink: "https://www.cleanenergycouncil.org.au/membership",
    },
    {
      id: "member-11",
      organization: "Australian Institute of Landscape Architects",
      type: "Graduate & Registered",
      benefits:
        "Continuing professional development, awards, advocacy on green infrastructure and climate-resilient places.",
      joinLink: "https://www.aila.org.au/membership",
    },
    {
      id: "member-12",
      organization: "Planning Institute of Australia",
      type: "Student & Full Membership",
      benefits:
        "National Congress, planning news, ethics and CPD, and networks across environmental and strategic planning.",
      joinLink: "https://www.planning.org.au/membership",
    },
  ],
};
